### ISSUE TITLE
Foreign error links lose type information

### ISSUE THREAD

**Issue by dflemstr** [brson/error-chain#4]
If I have a:

```rust
error_chain! {
    links {
        rustup_dist::Error, rustup_dist::ErrorKind, Dist;
        rustup_utils::Error, rustup_utils::ErrorKind, Utils;
    }
}
```

...and I do:

```rust
let e: Error = Error::from(rustup_dist::Error::Foo)
```

Then there is no way for me to get back a `rustup_dist::Error` instance from `e` that would let me determine whether it is a `rustup_dist::Error::Foo`.

I don't know if it's a good idea, but maybe `ErrorKind::Dist` could contain a type safe reference to the cause, and not have a boxed cause for that case?

**Comment by brson** [comment]
Thanks for the report.

Boxing the cause is a fundamental tradeoff of the crate's design, but you should be able to recover the concrete value by downcasting. You can pull out the box with `let (_, ref cause) = error;` then use [downcast_ref](https://doc.rust-lang.org/nightly/std/error/trait.Error.html#method.downcast_ref). Untested.

**Comment by brson** [comment]
The pattern needed is actually `let (_, (ref cause, _))`.

**Comment by dflemstr** [comment]
Got this approach to work after rubber ducking on IRC. Thanks for the help
