### ISSUE TITLE
Allow empty sections of macro to be excluded

### ISSUE THREAD

**Issue by brson** [brson/error-chain#6]
Most of the 'sections' of the macro can be empty, but it would be better if they could be excluded altogether. I'm just not good enough with macros to implement it.

**Comment by natemara** [comment]
It looks like there isn't a super easy way to make tokens in a macro optional, you would have to specify all possible token streams, which in this case would be 15 different rule sets for all of the different possibilities. I'm assuming that all 4 sections could be left out completely.

**Comment by natemara** [comment]
I think the simplest way to go about it would be to use a syntax plugin, but that would alienate anyone on stable.

**Comment by brson** [comment]
Is there a way to do it by matching zero-or more repetitions of a section, like `$( errors { $( $error_chunks:tt ) * } ) *`?

**Comment by natemara** [comment]
We could do that, my only concern with that was it would allow multiple
sections with the same name, but I guess since the other sections already
allow n repetitions of elements, it's not really a big deal. I think the
`types` section should probably stay as is for this reason.

On Jul 21, 2016 7:15 PM, "Brian Anderson" <notifications@github.com> wrote:

Is there a way to do it by matching zero-or more repetitions of a section,
like $( errors { $( $error_chunks:tt ) * } ) *?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/brson/error-chain/issues/6#issuecomment-234412266>, or mute
the thread

**Comment by brson** [comment]
Oh, good point. Hm. I can't think offhand why that would be bad...

**Comment by cramertj** [comment]
I tried this [here](https://github.com/cramertj/error-chain/tree/allow-missing-sections). However, I'm running into the recursion limit, and changing the limit causes rustc to overflow its stack. Any suggestions?
